pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/SixBlueBlack/mlops_practice', branch: 'master'
            }
        }

        stage('Install requirements') {
            steps {
                dir('lab2') {
                    bat 'pip install -r requirements.txt'
                }
            }
        }

        stage('Data Creation') {
            steps {
                dir('lab2') {
                    bat 'python data_creation.py'
                }
            }
        }

        stage('Model Preprocessing') {
            steps {
                dir('lab2') {
                    bat 'python model_preprocessing.py'
                }
            }
        }

        stage('Model Preparation') {
            steps {
                dir('lab2') {
                    bat 'python model_preparation.py'
                }
            }
        }

        stage('Model Testing') {
            steps {
                dir('lab2') {
                    bat 'python model_testing.py'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline выполнен успешно!'
        }
        failure {
            echo 'Pipeline завершился с ошибкой'
        }
    }
}